config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  namespace :admin  do 
    resources :restaurants
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end
  def new
    @restaurant = Restaurant.new
  end
  
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to  admin_restaurants_path
      flash[:notice] = "restaurant was successfully created"
    else
      render :new
      flash[:alert] = "restaurant was failed to create"
    end 
  end
  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alrt] = "restaurant was deleted"
  end
  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
      flash[:notice] = "restaurant was successfully update "
    else
      render :edit
      flash[:alert] = "restaurant was failed to update"
    end 
  end
  private 
  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image)
  end
  def set_restaurant
    @restaurant = Restaurant.find(params[:id]) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <div class="row">

    <% if @restaurant.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>

    <%= form_for [:admin, @restaurant] do |f| %>

      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :tel, "Tel" %>
        <%= f.text_field :tel, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :address, "Address" %>
        <%= f.text_field :address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :opening_hours, "Opening Hours" %>
        <%= f.text_field :opening_hours, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :image, "Photo" %>
        <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
        <%= f.file_field :image %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">
 
   <h1>餐廳後台</h1>
 
   <div class="row">
 
     <div class="col-md-12">
 
       <div>
         <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
       </div>
       <br>
       <table class="table table-striped table-bordered">
         <thead>
           <tr>
             <th>#</th>
             <th>Name</th>
             <th>#</th>
           </tr>
         </thead>
         <tbody>
           <% @restaurants.each do |restaurant| %>
           <tr>
             <th scope="row"><%= restaurant.id %></th>
             <td><%= restaurant.name %></td>
             <td>
               <%= link_to 'Show', admin_restaurant_path(restaurant) %>
               <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
               <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
             </td>
           </tr>
           <% end %>
         </tbody>
       </table>
 
       <div class="text-center">
         <%= paginate @restaurants %>
       </div>
 
     </div>
 
   </div>
 </div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%=form_for [:admin, @restaurant] do |f|%>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
   <div class="row">
     <div class="col-md-12">
       <h1><%= @restaurant.name %></h1>
     </div>
     <div class="col-md-4">
       <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
       <br>
       <div class="well">
         <ul class="list-unstyled">
           <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
           <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
           <li><strong>Address:</strong> <%= @restaurant.address %></li>
         </ul>
       </div>
     </div>
     <div class="col-md-8">
       <%= simple_format @restaurant.description %>
     </div>
     <div class="clearfix"></div>
     <hr>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

         <!-- 導覽列 -->
     <nav class="navbar navbar-default">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="#">餐廳評論網</a>
           <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
         </div>
 
         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
           <ul class="pull-right text-right nav navbar-nav">
             <% if current_user %>
                <% if current_user.admin? %>
                  <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
                <% end %>
             <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
             <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
             <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
             <% else %>
             <li><%= link_to('註冊', new_user_registration_path) %></li>
             <li><%= link_to('登入', new_user_session_path) %></li>
             <% end %>
           </ul>
         </div>
       </div>
     </nav>
     <% if flash[:notice] %>
     <div class="container">
       <div class="row">
         <div class="alert alert-success alert-dismissible" role="alert">
           <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <%= notice %>
         </div>
       </div>
     </div>
     <% end %>
 
     <% if flash[:alert] %>
     <div class="container">
       <div class="row">
         <div class="alert alert-danger alert-dismissible" role="alert">
           <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <%= alert %>
         </div>
       </div>
     </div>
     <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>餐廳前台</h1>